### ISSUE TITLE
readlink -m is an invalid option

### ISSUE THREAD

**Issue by hippyau** [sudo-give-me-coffee/wine-appimage#12]
Hi there,

 One target I have employs busybox, and complains when trying to run a bottle, that  -m is an invalid option for readlink, 

resulting in invalid WINEPREFIX, just after trying to start the executable.

how can I work around this?

Cheers, 
 Hip

**Comment by hippyau** [comment]
![image](https://user-images.githubusercontent.com/36442309/77390915-1bd26b00-6de3-11ea-881d-5847e11eeec3.png)

**Comment by probonopd** [comment]
Would `readlink -f` work instead?

**Comment by hippyau** [comment]
I can't figure out where it's being called from?

**Comment by probonopd** [comment]
I see it three times in `data/BottleTool.sh` as reported by

https://github.com/sudo-give-me-coffee/wine32-deploy/search?q=%22readlink+-m%22&unscoped_q=%22readlink+-m%22

**Comment by sudo-give-me-coffee** [comment]
This is a relatively old busybox ... I use -m because it also resolves when the directory is not found, however i fixed by adding `mkdir -p` before. Thanks for reporting this error

**Comment by probonopd** [comment]
jfyi, `readlink -f` also resolves if the target does not exist.

**Comment by hippyau** [comment]
Thanks so much, I'll try it out asap.
