### ISSUE TITLE
Minimize makes Appimage non-working

### ISSUE THREAD

**Issue by thenoobtester** [sudo-give-me-coffee/wine-appimage#19]
Hi, 

thanks for this great work. I looked for something like this for a long time.

When I run the minimze command and then package the Appimage doesn't work. I get:

`/tmp/.mount_SumatrALlRXc/wine: line 40: /tmp/.mount_SumatrALlRXc/lib/ld-linux.so.2: No such file or directory`

but when I skip Minimize it works (but the size difference is quite noticeable :)). I'm trying to package the SumatraPDF reader as an Appimage, it's one single .exe, no installation. I just copy it into Program Files/sumatraPDF and go from there.

Would you have any idea on what's happening.

Thank you.

PS:Debian Stretch 64bits

**Comment by sudo-give-me-coffee** [comment]
I'm working on it, this happens (at least in my tests) with Sumatra PDF only

**Comment by sudo-give-me-coffee** [comment]
@thenoobtester sorry for take a long time to response, with commit https://github.com/sudo-give-me-coffee/wine32-deploy/commit/82fee589a244298669056cbd8eb3c78403b90d21 seems to work. Can you try the new release?

**Comment by thenoobtester** [comment]
@sudo-give-me-coffee sorry for also taking time to respond. I will download it and let you know if it works. I have a slow internet speed so it will take time. Is there a way to do like a delta update? Thank you

**Comment by thenoobtester** [comment]
@sudo-give-me-coffee thank you for the reply and sorry for the response time but I have been sick as a dog for the past 5 days, which is probably why I re-downloaded the same Appimage as the first time. You asked if I could try the new release but I can't seem to find any. It's the same from January 17 which I downloaded again and it didn't work. Am I missing something?

Thank you for your help.

**Comment by sudo-give-me-coffee** [comment]
This is working for me

> "It's the same from January 17"

Is a GitHub bug i guess

**Comment by sudo-give-me-coffee** [comment]
Since it is possible to build an [functional AppImage](https://github.com/sudo-give-me-coffee/wine_recipes/releases/download/downloads/Sumatra-x86_64.AppImage) with [this commit](https://github.com/sudo-give-me-coffee/wine32-deploy/commit/9e469ce16b098441e89af86d0cbcbb55c26c1836), I will close this, feel free to reopen if necessary

**Comment by gotbletu** [comment]
looks like i got the same issue. it works if i do not use the **minimize** command

```
wine32-deploy-4.21-x86_64.AppImage minimize SpaceCadetPinball
wine32-deploy-4.21-x86_64.AppImage test SpaceCadetPinball
```
> [ 1/3 ] Creating Environment...
> 
> HOME=/tmp/tmp.ESiZtVAcq9
> XDG_CONFIG_HOME=/tmp/tmp.ESiZtVAcq9/config
> XDG_DATA_HOME=/tmp/tmp.ESiZtVAcq9/data
> WINEPREFIX=/tmp/tmp.ESiZtVAcq9/config/SpaceCadetPinball
> 
> [ 2/3 ] Initializing test...
> 
> /media/Bankai/WINEBOTTLE/SpaceCadetPinball.AppDir/wineserver: line 35: /media/Bankai/WINEBOTTLE/SpaceCadetPinball.AppDir/lib/ld-linux.so.2: No such file or directory
> /media/Bankai/WINEBOTTLE/SpaceCadetPinball.AppDir/wine: line 40: /media/Bankai/WINEBOTTLE/SpaceCadetPinball.AppDir/lib/ld-linux.so.2: No such file or directory
> 
> HOME=/tmp/tmp.ESiZtVAcq9
> XDG_CONFIG_HOME=/tmp/tmp.ESiZtVAcq9/config
> XDG_DATA_HOME=/tmp/tmp.ESiZtVAcq9/data
> WINEPREFIX=/tmp/tmp.ESiZtVAcq9/config/SumatraPDF
> 
> /media/Bankai/WINEBOTTLE/SpaceCadetPinball.AppDir/wine: line 40: /media/Bankai/WINEBOTTLE/SpaceCadetPinball.AppDir/lib/ld-linux.so.2: No such file or directory
> 
> [ 3/3 ] Ending test...
> 
> 

heres the game i used
https://www.myabandonware.com/game/space-cadet-3d-pinball-bc1#download
