### ISSUE TITLE
Cannot download from GitHub Releases

### ISSUE THREAD

**Issue by probonopd** [sudo-give-me-coffee/wine-appimage#3]
Sounds _very_ exciting. Can't wait to try it out.
But... the AppImage is missing on GitHub Releases.

**Comment by sudo-give-me-coffee** [comment]
My token was revoked by GitHub when I renamed the repository and didn't notice it. Many thanks for the reports. Please let me know if this problem persists.

**Comment by probonopd** [comment]
Thanks, excellent, the download is working for me now.
