### ISSUE TITLE
Copy-and-paste-able hello world

### ISSUE THREAD

**Issue by probonopd** [sudo-give-me-coffee/wine-appimage#4]
Hi, very cool project. Would it be possible to have a Copy-cand-paste-able hello world that would make an AppImage for a simple Windows app?

**Comment by sudo-give-me-coffee** [comment]
I am currently working on YAML based recipes similar to **pkg2appimage**, this is the reason for the absence of a "hello world". I wrote this script  to demonstration, is basically the same of [README.md](https://github.com/sudo-give-me-coffee/win32-appimage/blob/master/README.md#basic-usage) but using a real application:

```bash
#!/usr/bin/env bash

PATH=".:${PATH}"

download_urls=(
  "https://github.com/AppImage/AppImageKit/releases/download/continuous/appimagetool-x86_64.AppImage"
  "https://web.archive.org/web/2016/https://dl.google.com/picasa/picasa39-setup.exe"
  "https://github.com/sudo-give-me-coffee/win32-appimage/releases/download/continuous/Wine-4.21-x86_64.AppImage"
  )

# Download assets
wget -q -c --show-progress --progress=bar:force:noscroll ${download_urls[@]}

# Turns AppImages executables:
chmod +x *.AppImage

# Create the bottle
./Wine-4.21-x86_64.AppImage create-bottle "Picasa 3"

# Install Picasa
./Wine-4.21-x86_64.AppImage install       "Picasa 3" ./picasa39-setup.exe  /S /L

# Strip unneeded files:
./Wine-4.21-x86_64.AppImage --strip       "Picasa 3" mesa3D mono gecko style

# Remove application specific unneeded files (TODO: Native solution)
rm "Picasa_3/prefix/drive_c/Program Files/Google/Picasa3/PicasaPhotoViewer.exe"

# Create the package
./Wine-4.21-x86_64.AppImage package "Picasa 3"                                         \
                                    "C:/Program Files/Google/Picasa3/Picasa3.exe"      \
                                    "Graphics"                                         \
                                    "$(find ./Picasa_3 | grep Picasa3 | grep 256x256)"

# Build the AppImage
ARCH=x86_64 ./appimagetool-x86_64.AppImage "Picasa_3"
```

**Comment by sudo-give-me-coffee** [comment]
> Hi, very cool project. 

Thanks a lot. I hope that’s example is helpful, feel free to post any questions, report a problem or suggest a feature

**Comment by probonopd** [comment]
Very cool. I think I know a killer application, one that many Linux users would like to use but is traditionally very hard to get running properly on WINE:

https://gist.github.com/probonopd/0fab254aa0b6fc371d8db641822bd530#wine-on-linux

**Comment by probonopd** [comment]
Following the example given. Am I caught in an infinite loop? Would be good to know how many passes this will do...

```
Copying Wine32-AppImage...
Removing unneeded files...
Purging temporary dir...
Purging Gecko...
Removing Mesa32...
Purging Mono...
Deduplicating files...
Removing unnecessary bytes...
Purging temporary dir...
Deduplicating files...
Removing unnecessary bytes...
Purging temporary dir...
Deduplicating files...
Removing unnecessary bytes...
Purging temporary dir...
Deduplicating files...
Removing unnecessary bytes...
Purging temporary dir...
Deduplicating files...
Removing unnecessary bytes...
Purging temporary dir...
Deduplicating files...
Removing unnecessary bytes...
Purging temporary dir...
Deduplicating files...
Removing unnecessary bytes...
Purging temporary dir...
Deduplicating files...
```

**Comment by sudo-give-me-coffee** [comment]
> Am I caught in an infinite loop?

Yes and it's my fault, I'm sorry,

In this example script i has added this line:
```
PATH=".:${PATH}"
```
To avoid using `./` when calling `Wine-4.21-x86_64.AppImage`. The problem is that this  [commit](https://github.com/sudo-give-me-coffee/win32-appimage/commit/e7963b4b62ba2fc042eeb600a3415ed802ea46d1) commit was still sent to GitHub. So `strip` script is self calling instead calling the system `strip`.

> Would be good to know how many passes this will do...

Is 10 steps, generally done between 1 and 3 minutes, on a Celeron 450 with 2 Ghz
```
Copying Wine32-AppImage...
Removing unneeded files...
Purging temporary dir...
Purging Gecko...
Removing Mesa32...
Purging Mono...
Deduplicating files...
Removing unnecessary bytes...
Done!
Getting differential entries on regedit...
```
I will add a counter

**Comment by sudo-give-me-coffee** [comment]
In the case of Fusion 360, is a 32 bits application?

**Comment by probonopd** [comment]
Err, good point. I think it is 64bit.

**Comment by probonopd** [comment]
The Picasa example works great for me. So satisfying to see. Awesome work :+1: 

![](https://user-images.githubusercontent.com/2480569/72678436-cd7cb500-3a9d-11ea-8c4b-6ad8dc3a3213.png)
