### ISSUE TITLE
Further minimization

### ISSUE THREAD

**Issue by probonopd** [sudo-give-me-coffee/wine-appimage#5]
What is the theory of operation for the current minimization strategy?

By examining, at runtime, which files are actually needed, it may be possible to bring down the AppImage size even further, by bundling a narrower subset of Wine and its dependencies (only those that are actually needed by the particular app).

Here is a comparison:

![](https://user-images.githubusercontent.com/2480569/72678562-0cf7d100-3a9f-11ea-86ad-09d0f7ef2e47.png)

Using the minimization technique outlined in https://github.com/probonopd/libhookexecv#minimizing I was able to reduce the size by more than three quarters!

**Comment by sudo-give-me-coffee** [comment]
It's amazing, please, can you send me the minimized version? I didn't understand which step should I take to perform these steps

**Comment by sudo-give-me-coffee** [comment]
I was able to reduce the size to 158 MB following the same logic and "reverse engineering" the **NotepadPlusPlus-3.5-x86_64.AppImage** without affect resulting AppImage. It's very impressive, but 100 MB is floating under AppImage if compared  with your

**Comment by mmtrt** [comment]
Why not make the wine appimage act as runtime and create split windows software appimages containing application + script launchers without wine so it leverages the actual wine runtime appimage to run and this make appimage size as actual application size.

Sample appimage I did way back uses same technique https://github.com/mmtrt/foobar2000_AppImage

Just my opinion.

**Comment by probonopd** [comment]
The steps:

```
mkdir squashfs-root
sudo mount -t tmpfs tmpfs squashfs-root/ -o strictatime,nodiratime 
./Picasa_3-x86_64.AppImage --appimage-extract 

touch test

./squashfs-root/AppRun

find squashfs-root/ -mindepth 3 -anewer test -not -path '*/share/icons/*' -not -path '*/share/applications/*' -not -path '*/share/metainfo/*' 
find squashfs-root/ -mindepth 3 -not -anewer test -not -path '*/share/icons/*' -not -path '*/share/applications/*' -not -path '*/share/metainfo/*' -delete || true
find squashfs-root/ -type d -empty -delete
./squashfs-root/AppRun  # Does it still run?

# Make minimized AppImage
ARCH=x86_64 ./appimagetool-x86_64.AppImage ./squashfs-root/
```

Example: https://github.com/probonopd/libhookexecv/releases/download/continuous/Picasa_3-minimized-x86_64.AppImage

**Comment by probonopd** [comment]
> Why not make the wine appimage act as runtime and create split windows software appimages containing application + script launchers without wine so it leverages the actual wine runtime appimage to run and this make appimage size as actual application size.

An AppImage must contain everything to run the application. Otherwise it is not an AppImage. The whole idea of AppImage is "one app = one file". This makes AppImages so simple to use.

Also, my method of minimizing the AppImage means that the AppImage just contains enough of Wine to run __this__ Windows application, but not others.

**Comment by sudo-give-me-coffee** [comment]
Very cool, ~now I see where my error is,~ I will implement this as an option, thank you very much @probonopd

**Comment by sudo-give-me-coffee** [comment]
> Why not make the wine appimage act as runtime and create split windows software appimages containing application + script launchers without wine so it leverages the actual wine runtime appimage to run and this make appimage size as actual application size.
> 
> Sample appimage I did way back uses same technique https://github.com/mmtrt/foobar2000_AppImage
> 
> Just my opinion.

The first reason, is the @probonopd reply
 
The second reason is that, on Windows, the program is distributed with all the content. In linux, in my opinion, this should be better, all application dependencies must be contained in a single file to avoid installations

@mmtrt, thanks for your idea, but it has a some issues, for e.g. if user uses a ostree managed system?

**Comment by mmtrt** [comment]
@probonopd @sudo-give-me-coffee Sure my method is flawed and has some issues like segfaults when calling some scripts from other appimage and it breaks AppImage philosophy as single app file and could create issues with ostree system in long run but yet it has more stability as compare to minimized version of Appimage which tends to break due to missing files removed by using that method.

Back to testing this appimage:

I did some testing on packaging bottles they seems to work fine good job on making this possible but during test one app failed to launched after being packed as AppImage which was notepad-plus-plus where its own dll signature protection failed to launch due to that but this worked fine on launching it from bottle after installed.

**Comment by sudo-give-me-coffee** [comment]
@mmtrt Can you please open a separate "Issue" for this? I found the source of the bug, but I need a separate "issue" to reference with the fix

**Comment by sudo-give-me-coffee** [comment]
@probonopd This method is clearing plugins and additional data, licenses, change logs and  all other "secondary" resources

**Comment by probonopd** [comment]
Yes. Maybe it is necessary to exclude some locations from being deleted.

**Comment by sudo-give-me-coffee** [comment]
@probonopd  Added "minimize" option

**Comment by sudo-give-me-coffee** [comment]
@mmtrt  added option to bundle  system.reg file

**Comment by sudo-give-me-coffee** [comment]
Many thanks, i think that i can close now, if not please reopen it

**Comment by probonopd** [comment]
> @probonopd Added "minimize" option

How does it work?

**Comment by sudo-give-me-coffee** [comment]
Essentially the same as you went through, but with some differences to ensure that regedit is packaged

1. Creates a empty `${HOME}` and mount point for AppDir

https://github.com/sudo-give-me-coffee/win32-appimage/blob/5834160a476be8d24f221be1c51287102aa876c0/data/AppDirTool.sh#L115-L117
2. Mount the `TMPFS_APPDIR` like you:
https://github.com/sudo-give-me-coffee/win32-appimage/blob/5834160a476be8d24f221be1c51287102aa876c0/data/AppDirTool.sh#L126

3. Copies AppDir to `TMPFS_APPDIR` 

https://github.com/sudo-give-me-coffee/win32-appimage/blob/5834160a476be8d24f221be1c51287102aa876c0/data/AppDirTool.sh#L130

3. Creates the reference file and run:

https://github.com/sudo-give-me-coffee/win32-appimage/blob/5834160a476be8d24f221be1c51287102aa876c0/data/AppDirTool.sh#L134-L135

4. Collects unused files and remove them:

https://github.com/sudo-give-me-coffee/win32-appimage/blob/5834160a476be8d24f221be1c51287102aa876c0/data/AppDirTool.sh#L139-L148
