### ISSUE TITLE
How are you handling $WINEPREFIX?

### ISSUE THREAD

**Issue by probonopd** [sudo-give-me-coffee/wine-appimage#6]
Are you using something along the lines of https://github.com/AppImage/AppImageKit/wiki/Bundling-Windows-applications#3-make-it-possible-to-use-a-read-only-wineprefix or another trick to make it possible to use a read-only `$WINEPREFIX` inside the AppImage?

**Comment by sudo-give-me-coffee** [comment]
Meu plano originalmente era usar unionfs. Mas vi alguns problemas com essa abordagem, como o unionfs que depende do FUSE que não está disponível na maioria das caixas de proteção, another important thing is when use:
```
echo "disable" > "$WINEPREFIX/.update-timestamp" 
```
Wine does not update user sources or directories, for these and other reasons, I do not use read-only prefixes, such as a `Wine Bottler`, `Wineskin` or `Wine_AppImage`. `Win32-appimage` just creates a separate folder in `${XDG_CONFIG_HOME}` with the name of the bottle, then creates symbolic links to folders in the drive_c directories in AppImage and updates the prefix in `${HOME}`. In the end, only 530 KB is written to the disk.

----------------------------

In practice, the user has a fully functional prefix, but with no possibility of writing to directories that, in Windows, he also does not have
```
system.reg
userdef.reg
user.reg
.update-timestamp
default.reg
drive_c
drive_c/users/${USER}
```

**Comment by probonopd** [comment]
Thanks for the explanation, I understand.
